# GBO-Aku https://www.yorix.cz/cz/greenbono/gbo-aku.htm
substitutions:
  friendly_name: D1 mini pro
  device_name: d1-mini-pro

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_pass
  # use_address: 192.168.4.1
  fast_connect: true
  manual_ip:
    static_ip: 192.168.1.200
    gateway: 192.168.1.1
    subnet: 255.255.255.0
  ap:
    ssid: "${device_name}"
    # captive_portal:

mdns:
  disabled: true

captive_portal:

web_server:
  port: 80

ota:

esphome:
  name: $device_name

esp8266:
  board: d1_mini_pro

logger:
  level: VERY_VERBOSE
  hardware_uart: UART0_SWAP

uart:
  id: mod_bus
  tx_pin: GPIO1
  rx_pin: GPIO3
  baud_rate: 9600
  debug:

modbus:
  id: modbus_greenbono

modbus_controller:
  - id: greenbono
    address: 1
    modbus_id: modbus_greenbono
    update_interval: 10s

sensor:
  - platform: modbus_controller
    modbus_controller_id: greenbono
    id: last_valid_i1
    name: ${friendly_name} LastValidI1
    address: 8
    unit_of_measurement: "A"
    register_type: read
    value_type: S_WORD
    accuracy_decimals: 1
    filters:
      - multiply: 0.01

  - platform: modbus_controller
    modbus_controller_id: greenbono
    id: last_valid_u1
    name: ${friendly_name} LastValidU1
    address: 16
    unit_of_measurement: "V"
    register_type: read
    value_type: U_WORD
    accuracy_decimals: 0
