---
substitutions:
  friendly_name: esp32-c3
  device_name: esp32-c3

<<: !include common.yaml
<<: !include wifi-cakovice.yaml

esphome:
  name: $friendly_name
  platformio_options:
    board_build.mcu: esp32c3
    board_build.variant: esp32c3

esp32:
  board: esp32-c3-devkitm-1
  variant: ESP32C3
  framework:
    type: esp-idf

logger:
  level: DEBUG
