---
substitutions:
  friendly_name: esp32-c3
  device_name: esp32-c3

<<: !include common.yaml
<<: !include wifi-cakovice.yaml

esphome:
  name: $friendly_name
  platformio_options:
    board_build.mcu: esp32c3
    board_build.variant: esp32c3

esp32:
  board: esp32-c3-devkitm-1
  variant: ESP32C3
  framework:
    type: arduino

logger:
  level: DEBUG

uart:
  id: mod_bus
  tx_pin: GPIO21
  rx_pin: GPIO20
  baud_rate: 9600

light:
  - platform: status_led
    name: "Status LED"
    id: esp_status_led
    icon: "mdi:alarm-light"
    pin:
      number: GPIO8
      inverted: true
    restore_mode: ALWAYS_OFF
