# GBO-Aku https://www.yorix.cz/cz/greenbono/gbo-aku.htm
# modbus protocol: https://www.yorix.cz/cz/download/GBO_modbus.zip

substitutions:
  friendly_name: Greenbono
  device_name: greenbono

<<: !include common.yaml
<<: !include wifi-ufo8.yaml

esphome:
  name: $device_name
  on_boot:
    priority: -100
    then:
      - delay: 30s
      - lambda: |-
          // get local time and sync to controller
          time_t now = ::time(nullptr);
          struct tm *time_info = ::localtime(&now);
          int second = time_info->tm_sec;
          int minute = time_info->tm_min;
          int hour = time_info->tm_hour;
          int wday = time_info->tm_wday;
          int day = time_info->tm_mday;
          int month = time_info->tm_mon + 1;
          int year = time_info->tm_year % 100;
          esphome::modbus_controller::ModbusController *controller = id(greenbono);
          // if there is no internet connection localtime returns year 70
          if (year != 70)
          {
            // create the payload
            std::vector<uint16_t> rtc_data = {uint16_t((minute << 8) | second),
                                              uint16_t((wday << 8) | hour),
                                              0x0955,
                                              uint16_t((month << 8) | day),
                                              uint16_t(year)};
            // Create a modbus command item with the time information as the payload
            ESP_LOGI("ModbusLambda", "%02d:%02d:%02d %02d.%02d.%04d",
                    hour, minute, second, day, month, year + 2000);
            esphome::modbus_controller::ModbusCommandItem set_rtc_command =
                esphome::modbus_controller::ModbusCommandItem::create_write_multiple_command(
                    controller, 0x0, rtc_data.size(), rtc_data);
            controller->queue_command(set_rtc_command);
          }

esp8266:
  board: d1_mini_pro

logger:
  level: VERBOSE
  baud_rate: 0

uart:
  id: mod_bus
  tx_pin: GPIO01
  rx_pin: GPIO03
  baud_rate: 9600

modbus:
  id: modbus_greenbono

modbus_controller:
  - id: greenbono
    address: 0x01
    modbus_id: modbus_greenbono
    # command_throttle: 100ms
    update_interval: 10s

sensor:
  - platform: wifi_signal
    name: $friendly_name Wifi RSSI
    update_interval: 60s

  - platform: modbus_controller
    modbus_controller_id: greenbono
    id: last_valid_i1
    name: ${friendly_name} LastValidI1
    address: 8
    unit_of_measurement: "A"
    register_type: read
    value_type: S_WORD
    accuracy_decimals: 1
    filters:
      - multiply: 0.1

  - platform: modbus_controller
    modbus_controller_id: greenbono
    id: last_valid_u1
    name: ${friendly_name} LastValidU1
    address: 16
    unit_of_measurement: "V"
    register_type: read
    value_type: U_WORD

  - platform: template
    id: last_valid_p1
    name: ${friendly_name} LastValidP1
    unit_of_measurement: "W"
    lambda: |-
      return id(last_valid_i1).state * id(last_valid_u1).state * -1;
    update_interval: 60s

  - platform: modbus_controller
    modbus_controller_id: greenbono
    id: ssr1
    name: ${friendly_name} SSR
    unit_of_measurement: "%"
    address: 18
    register_type: read
    value_type: U_WORD
    bitmask: 0x00FF
    filters:
      - calibrate_linear:
        - 0 -> 0
        - 255 -> 100

  - platform: modbus_controller
    modbus_controller_id: greenbono
    id: i_ssr1
    name: ${friendly_name} I_SSR1
    address: 26
    unit_of_measurement: "A"
    register_type: read
    value_type: S_WORD
    accuracy_decimals: 1
    # filters:
    #   - multiply: 0.1

  - platform: modbus_controller
    modbus_controller_id: greenbono
    id: eessrlevelfork1on
    name: ${friendly_name} SSR Level For K1 On
    unit_of_measurement: "%"
    register_type: holding
    address: 108
    bitmask: 0x00FF
    skip_updates: 5
    filters:
      - calibrate_linear:
        - 0 -> 0
        - 255 -> 100

  - platform: modbus_controller
    modbus_controller_id: greenbono
    id: eessrlevelfork2on
    name: ${friendly_name} SSR Level For K2 On
    unit_of_measurement: "%"
    register_type: holding
    address: 110
    bitmask: 0x00FF
    skip_updates: 5
    filters:
      - calibrate_linear:
        - 0 -> 0
        - 255 -> 100

binary_sensor:
  - platform: modbus_controller
    modbus_controller_id: greenbono
    id: k1_relay_status
    name: ${friendly_name} K1 Relay Status
    register_type: holding
    address: 10
    bitmask: 0x0001

  - platform: modbus_controller
    modbus_controller_id: greenbono
    id: k2_relay_status
    name: ${friendly_name} K2 Relay Status
    register_type: holding
    address: 10
    bitmask: 0x0002

  - platform: modbus_controller
    modbus_controller_id: greenbono
    id: k3_relay_status
    name: ${friendly_name} K3 Relay Status
    register_type: holding
    address: 10
    bitmask: 0x0004

  - platform: modbus_controller
    modbus_controller_id: greenbono
    id: k4_relay_status
    name: ${friendly_name} K4 Relay Status
    register_type: holding
    address: 10
    bitmask: 0x0008

  - platform: modbus_controller
    modbus_controller_id: greenbono
    id: k5_relay_status
    name: ${friendly_name} K5 Relay Status
    register_type: holding
    address: 10
    bitmask: 0x0010

text_sensor:
  - platform: modbus_controller
    modbus_controller_id: greenbono
    id: t_datetime
    name: ${friendly_name} t_datetime
    address: 0
    register_type: holding
    register_count: 5
    lambda: |-
      char buffer[26];
      snprintf(buffer, sizeof(buffer), "%02d:%02d:%02d %02d.%02d.%04d",
        data[3], data[0], data[1], data[7], data[6], (data[8] << 8 | data[9]) + 2000);
      return {buffer};
    skip_updates: 5

  - platform: modbus_controller
    modbus_controller_id: greenbono
    id: firmware_version
    name: ${friendly_name} EEfwVersion
    address: 34
    raw_encode: HEXBYTES
    register_type: holding
    lambda: |-
      char buffer[7];
      uint16_t value = modbus_controller::word_from_hex_str(x, 0);
      snprintf(buffer, sizeof(buffer), "%01d.%03d", value/1000, value % 1000);
      return {buffer};
    skip_updates: 5

  - platform: modbus_controller
    modbus_controller_id: greenbono
    id: sh2starttime0
    name: ${friendly_name} SH2StartTime0
    address: 52
    register_type: holding
    lambda: |-
      int minute = data[0];
      int hour = data[1];
      if (hour != 255)
      {
        char buffer[8];
        snprintf(buffer, sizeof(buffer), "%02d:%02d", hour, minute);
        return {buffer};
      } else {
        return {"OFF"};
      }
    skip_updates: 5

  - platform: modbus_controller
    modbus_controller_id: greenbono
    id: sh2stoptime0
    name: ${friendly_name} SH2StopTime0
    address: 54
    register_type: holding
    lambda: |-
      int minute = data[0];
      int hour = data[1];
      if (hour != 255)
      {
        char buffer[8];
        snprintf(buffer, sizeof(buffer), "%02d:%02d", hour, minute);
        return {buffer};
      } else {
        return {"OFF"};
      }
    skip_updates: 5
