# GBO-Aku https://www.yorix.cz/cz/greenbono/gbo-aku.htm
substitutions:
  friendly_name: Greenbono
  device_name: greenbono

<<: !include common.yaml

esphome:
  name: $device_name
  platform: ESP8266
  board: esp12e

logger:
  level: VERY_VERBOSE
  # baud_rate: 0

# i2c:
#   sda: D1
#   scl: D2
#   scan: false

# display:
#   - platform: ssd1306_i2c
#     model: "SH1106 128x64"
#     address: 0x3C
#     lambda: |-
#       it.print(0, 0, id(font), "Hello World!");

uart:
  id: mod_bus
  tx_pin: GPIO4
  rx_pin: GPIO5
  baud_rate: 9600
  stop_bits: 1

modbus:
  id: modbus_greenbono

modbus_controller:
  - id: greenbono
    address: 0x01
    modbus_id: modbus_greenbono
    update_interval: 60s

sensor:
  - platform: modbus_controller
    modbus_controller_id: greenbono
    id: last_valid_i1
    name: ${friendly_name} LastValidI1
    address: 8
    unit_of_measurement: "A"
    register_type: read
    value_type: S_WORD
    accuracy_decimals: 1
    filters:
      - multiply: 0.01

  - platform: modbus_controller
    modbus_controller_id: greenbono
    id: last_valid_u1
    name: ${friendly_name} LastValidU1
    address: 16
    unit_of_measurement: "V"
    register_type: read
    value_type: S_WORD
    accuracy_decimals: 0

  - platform: modbus_controller
    modbus_controller_id: greenbono
    id: output_pi
    name: ${friendly_name} OutputPI
    address: 18
    register_type: read
    value_type: U_WORD
    bitmask: 0x00FF
    accuracy_decimals: 0
