---
substitutions:
  device_name: openbk7231n-b976ac0b
  friendly_name: OpenBK7231N_B976AC0B

esphome:
  name: ${device_name}

<<: !include common.yaml

# CBU Wi-Fi Module https://docs.libretiny.eu/boards/cbu/
bk72xx:
  board: cbu
  framework:
    version: dev
  family: bk7231n

#Beken chips, unlike ESP, do not have an RTC memory for storing data. The settings are saved in flash memory every 10 minutes, not every time you change. If you need to shorten the time, then use the code below

#https://github.com/libretiny-eu/libretiny/issues/75
#https://github.com/libretiny-eu/libretiny/issues/41
preferences:
  flash_write_interval: 1min

# Enable logging
logger:

output:
  - id: idLedOutput
    platform: gpio
    pin:
      number: P15
      inverted: true
      mode:
        output: true

switch:
  - platform: template
    name: $friendly_name
    id: idSwitch
    icon: mdi:light-switch
    turn_on_action:
      - switch.turn_on: idONRelay
    turn_off_action:
      - switch.turn_on: idOFFRelay
    optimistic: true
    internal: false #Hide - true \show - false
    restore_mode: RESTORE_DEFAULT_ON

  - platform: gpio
    pin:
      number: P24
      inverted: true
    id: idOFFRelay
    name: "OFF Relay"
    restore_mode: ALWAYS_OFF
    internal: True #Hide - true \show - false
    interlock: [idONRelay]
    on_turn_on:
      - light.turn_off: idLed
      - binary_sensor.template.publish:
          id: idSwitchState
          state: OFF
      - delay: 100ms
      - switch.turn_off: idOFFRelay

  - platform: gpio
    pin:
      number: P26
      inverted: true
    id: idONRelay
    name: "ON Relay"
    restore_mode: ALWAYS_OFF
    internal: True #Hide - true \show - false
    interlock: [idOFFRelay]
    on_turn_on:
      - light.turn_on: idLed
      - binary_sensor.template.publish:
          id: idSwitchState
          state: ON
      - delay: 100ms
      - switch.turn_off: idONRelay

light:
  - platform: binary
    name: $friendly_name LED
    id: idLed
    output: idLedOutput
    internal: true #Hide - true \show - false

# sensor:
#   - platform: wifi_signal
#     name: $friendly_name WiFi RSSI
#     update_interval: 60s

binary_sensor:
  - platform: gpio
    pin:
      number: P17
      inverted: true
      mode:
        input: true
    name: "Button"
    icon: mdi:flash
    id: idHardButton
    on_press:
      switch.toggle: idSwitch
    internal: true
  - platform: template
    name: Switch State
    icon: mdi:light-switch
    id: idSwitchState
