# Siton 210
# source: https://github.com/TataGEEK/Siton210/blob/main/siton210.yaml

substitutions:
  #komunikační piny, pokud používáte originální desku Siton WiFi modulu, nic neměňte
  rxPin: GPIO3
  txPin: GPIO1
  device_name: "siton210" #název zařízení
  updates: 60s #četnost aktualizací
  adresa: "12" #ID meniče/adresa. Výchozí adresa Sitonu je 12 (0x0C)


<<: !include common.yaml
<<: !include wifi-ufo8.yaml

esphome:
  name: siton210

esp8266:
  board: esp01_1m

uart:
  id: mod_bus
  tx_pin: ${txPin}
  rx_pin: ${rxPin}
  baud_rate: 9600
  stop_bits: 1

modbus:
  send_wait_time: 500ms
  id: mod_bus_siton210

modbus_controller:
  - id: siton210
    address: ${adresa}
    modbus_id: mod_bus_siton210
    command_throttle: 0ms
    setup_priority: -10
    update_interval: ${updates}

sensor:
  - platform: modbus_controller
    modbus_controller_id: siton210
    id: napeti
    name: "${device_name} Voltage"
    state_class: measurement
    device_class: voltage
    address: 0x0004
    unit_of_measurement: "V"
    icon: mdi:sine-wave
    #icon: mdi:square-wave
    register_type: holding
    value_type: U_WORD
    accuracy_decimals: 0

  - platform: modbus_controller
    modbus_controller_id: siton210
    id: proud
    name: "${device_name} Current"
    state_class: measurement
    device_class: current
    address: 0x0005
    unit_of_measurement: "A"
    icon: mdi:pulse
    #icon: mdi:lightning-bolt
    register_type: holding
    value_type: U_WORD
    accuracy_decimals: 2
    filters:
      - multiply: 0.01

  - platform: modbus_controller
    modbus_controller_id: siton210
    id: vykon
    name: "${device_name} Power"
    address: 0x0006
    state_class: measurement
    device_class: power
    unit_of_measurement: "W"
    icon: mdi:solar-power
    register_type: holding
    value_type: U_WORD
    accuracy_decimals: 0

  - platform: modbus_controller
    modbus_controller_id: siton210
    id: teplota
    name: "${device_name} Temperature"
    state_class: measurement
    device_class: temperature
    address: 0x0007
    unit_of_measurement: "°C"
    register_type: holding
    value_type: U_WORD
    accuracy_decimals: 0

  - platform: modbus_controller
    modbus_controller_id: siton210
    id: vyroba
    name: "${device_name} Energy kWh"
    state_class: total_increasing
    device_class: energy
    address: 0x000C
    unit_of_measurement: "kWh"
    icon: mdi:chart-bell-curve-cumulative
    register_type: holding
    value_type: U_DWORD_R
    accuracy_decimals: 3
    filters:
      - multiply: 0.001

  - platform: wifi_signal
    name: "${device_name} WiFi Signal"
    entity_category: diagnostic
    disabled_by_default: true

text_sensor:
  - platform: wifi_info
    scan_results:
      name: "${device_name} Latest Scan Result"
      entity_category: diagnostic
      disabled_by_default: true
