# Siton 210 with EasyTransfer
# source: https://github.com/TataGEEK/Siton210/blob/main/siton210.yaml

substitutions:
  device_name: "siton210" # název zařízení
  updates: 60s # četnost aktualizací

<<: !include common.yaml
<<: !include wifi-ufo8.yaml

esphome:
  name: $device_name
  on_boot:
    priority: -100
    then:
      # reconnect to solar AP
      - delay: 60s
      - wifi.disable
      - wifi.enable

esp8266:
  board: esp01_1m

logger:
  level: VERBOSE
  baud_rate: 0

uart:
  tx_pin: TX
  rx_pin: RX
  baud_rate: 9600
  stop_bits: 1
  debug:
    direction: RX
    dummy_receiver: true
    sequence:
      - lambda: |-
          UARTDebug::log_int(direction, bytes, ',');
          if ((bytes[0] == 0x06) && (bytes[1] == 0x85)) {
            id(napeti).publish_state(word(bytes[8], bytes[7]));
            id(proud).publish_state(word(bytes[10], bytes[9]));
            id(vykon).publish_state(word(bytes[12], bytes[11]));
            id(temperature).publish_state(word(bytes[14], bytes[13]));
            id(vyroba).publish_state(bytes[26] << 24 | bytes[25] << 16
                                     | bytes[24] << 8 | bytes[23]);
          }

sensor:
  - platform: template
    name: "${device_name} Voltage"
    id: napeti
    state_class: measurement
    device_class: voltage
    unit_of_measurement: "V"
    icon: mdi:sine-wave
    accuracy_decimals: 0

  - platform: template
    id: proud
    name: "${device_name} Current"
    state_class: measurement
    device_class: current
    unit_of_measurement: "A"
    icon: mdi:pulse
    accuracy_decimals: 2
    filters:
      - multiply: 0.01

  - platform: template
    id: vykon
    name: "${device_name} Power"
    state_class: measurement
    device_class: power
    unit_of_measurement: "W"
    icon: mdi:solar-power
    accuracy_decimals: 0

  - platform: template
    name: "${device_name} Temperature"
    id: temperature
    state_class: measurement
    device_class: temperature
    unit_of_measurement: "°C"
    accuracy_decimals: 0

  - platform: template
    name: "${device_name} Energy kWh"
    id: vyroba
    state_class: total_increasing
    device_class: energy
    unit_of_measurement: "kWh"
    icon: mdi:chart-bell-curve-cumulative
    accuracy_decimals: 1
    filters:
      - multiply: 0.001

  - platform: wifi_signal
    name: "${device_name} WiFi Signal"
    entity_category: diagnostic
    update_interval: 60s
