---
substitutions:
  friendly_name: Sonoff S20-02
  device_name: sonoff-s20-02

esphome:
  name: ${device_name}
  on_boot: # Set the initial state of the realy to ON
    priority: 250.0 # Wait until WiFi is connected to allow the sensor some time to settle
    then:
      - switch.turn_on: relay

esp8266:
  board: esp01_1m

<<: !include common.yaml
<<: !include wifi-ufo8.yaml

sensor:
  - platform: wifi_signal
    name: ${device_name} Wifi RSSI
    update_interval: 60s

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO0
      mode: INPUT_PULLUP
      inverted: True
    id: button
    on_press:
      - switch.toggle: relay

switch:
  - platform: gpio
    name: $friendly_name
    pin: GPIO12
    id: relay

time:
  - platform: homeassistant
    id: homeassistant_time
    timezone: Europe/Prague
    on_time:
      # switch ON
      - seconds: 00
        minutes: 00
        hours: 16
        days_of_week: MON-SUN
        then:
          - switch.turn_on: relay

      # switch OFF Every night
      - seconds: 00
        minutes: 00
        hours: 23
        days_of_week: MON-SUN
        then:
          - switch.turn_off: relay
