---
substitutions:
  device_name: kids-light

esphome:
  name: ${device_name}
  platform: ESP8266
  board: esp01_1m

<<: !include common.yaml

binary_sensor:
  - platform: gpio
    id: button
    pin:
      number: GPIO0
      mode: INPUT_PULLUP
      inverted: True
    on_press:
      - light.toggle: ${device_name}

output:
  - platform: gpio
    id: light_relay
    pin: GPIO12

light:
  - platform: binary
    id: ${device_name}
    name: ${device_name}
    output: light_relay
