esphome:
  name: sonoff_s20
  platform: ESP8266
  board: esp01_1m
  board_flash_mode: dout

wifi:
  ssid: "jiricek"
  password: "vQjDJVsMLLFsyKyFs6q"

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:
