substitutions:
  esphome_name: sonoff_pow_christmas

esphome:
  name: ${esphome_name}
  platform: ESP8266
  board: esp01_1m

<<: !include common.yaml

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO0
      mode: INPUT_PULLUP
      inverted: True
    id: button
    on_press:
      - switch.toggle: relay

switch:
  - platform: gpio
    name: dortik
    pin: GPIO12
    id: relay

# temp sensor: Rx pin GPIO3
#dallas:
#  - pin: GPIO3
#
#  # temp sensor
#  - platform: dallas
#    address: 0xA40000055D2B4128
#    name: "${esphome_name} temperature"
#
