---
substitutions:
  friendly_name: Sonoff S20-02
  device_name: sonoff-s20-02

esphome:
  name: ${device_name}
  platform: ESP8266
  board: esp01_1m
  on_boot: # Set the initial state of the realy to ON
    priority: 250.0 # Wait until WiFi is connected to allow the sensor some time to settle
    then:
      - switch.turn_on: relay

<<: !include common.yaml
<<: !include wifi-ufo8.yaml

sensor:
  - platform: wifi_signal
    name: ${device_name} Wifi RSSI
    update_interval: 60s

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO0
      mode: INPUT_PULLUP
      inverted: True
    id: button
    on_press:
      - switch.toggle: relay

switch:
  - platform: gpio
    name: $friendly_name
    pin: GPIO12
    id: relay

# switch sunrise and sunset
sun:
  latitude: !secret latitude_semanovice
  longitude: !secret longitude_semanovice

  # switch ON
  on_sunset:
    - then:
        - switch.turn_on: relay

  # switch OFF
  on_sunrise:
    - then:
        - switch.turn_off: relay
