substitutions:
  esphome_name: sonoff_pow_tv

esphome:
  name: ${esphome_name}
  platform: ESP8266
  board: esp01_1m

<<: !include common.yaml

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO0
      mode: INPUT_PULLUP
      inverted: True
    id: button
    on_press:
      - switch.toggle: relay

switch:
  - platform: gpio
    name: emmet
    pin: GPIO12
    id: relay
