---
substitutions:
  esphome_name: sonoff-s20-01

esphome:
  name: ${esphome_name}
  platform: ESP8266
  board: esp01_1m

<<: !include common.yaml

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO0
      mode: INPUT_PULLUP
      inverted: True
    id: button
    on_press:
      - switch.toggle: relay

switch:
  - platform: gpio
    name: ${esphome_name}
    pin: GPIO12
    id: relay


# switch ON/OFF
time:
  - platform: sntp
    id: sntp_time
    timezone: Europe/Prague
    on_time:
      # switch ON
      - seconds: 00
        minutes: 00
        hours: 08
        days_of_week: MON-SUN
        then:
          - switch.turn_on: relay

      # OFF Every evening
      - seconds: 00
        minutes: 00
        hours: 00
        days_of_week: MON-SUN
        then:
          - switch.turn_off: relay
