---
substitutions:
  friendly_name: Sonoff Mini 01
  device_name: sonoff_mini

esphome:
  name: ${device_name}
  platform: ESP8266
  board: esp01_1m

<<: !include common.yaml

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO04
      mode: INPUT_PULLUP
      inverted: True
    id: mini_switch_1
    # schodistak, nastaveno na zmenu stavu
    on_state:
      then:
        - switch.toggle: relay_1

switch:
  - platform: gpio
    name: $friendly_name
    pin: GPIO12
    id: relay_1
