---
substitutions:
  friendly_name: Sonoff Pow Christmas
  device_name: sonoff-pow-christmas

esphome:
  name: ${device_name}
  platform: ESP8266
  board: esp01_1m

<<: !include common.yaml

i2c:
  sda: GPIO3
  scl: GPIO1
  scan: True

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO0
      mode: INPUT_PULLUP
      inverted: True
    id: button
    on_press:
      - switch.toggle: relay

sensor:
  - platform: sht3xd
    temperature:
      id: sht31_temp
      name: "${friendly_name} Temperature"
    humidity:
      id: sht31_humid
      name: "${friendly_name} Humidity"
    address: 0x44
    update_interval: 60s

switch:
  - platform: gpio
    name: $friendly_name
    pin: GPIO12
    id: relay

# switch ON
sun:
  latitude: !secret latitude
  longitude: !secret longitude
  # switch ON
  on_sunset:
    - then:
        - switch.turn_on: relay

# switch OFF
time:
  - platform: homeassistant
    id: homeassistant_time
    timezone: Europe/Prague
    on_time:
      # OFF Every evening
      - seconds: 00
        minutes: 00
        hours: 22
        days_of_week: MON-SUN
        then:
          - switch.turn_off: relay
