---
substitutions:
  esphome_name: sonoff_s20_flower

esphome:
  name: ${esphome_name}
  platform: ESP8266
  board: esp01_1m

<<: !include common.yaml

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO0
      mode: INPUT_PULLUP
      inverted: True
    id: button
    on_press:
      - switch.toggle: relay

switch:
  - platform: gpio
    name: flower
    pin: GPIO12
    id: relay

sun:
  latitude: !secret latitude
  longitude: !secret longitude
  # switch ON
  on_sunset:
  - then:
    - switch.turn_on: relay

time:
  - platform: homeassistant
    id: homeassistant_time
    timezone: Europe/Prague
    on_time:
      # OFF Every evening
      - seconds: 00
        minutes: 00
        hours: 22
        days_of_week: MON-SUN
        then:
          - switch.turn_off: relay
