substitutions:
  esphome_name: sonoff-pow-christmas

esphome:
  name: ${esphome_name}
  platform: ESP8266
  board: esp01_1m

<<: !include common.yaml

# Disable logging over USB
logger:
  baud_rate: 0

uart:
  rx_pin: RX
  baud_rate: 4800

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO0
      mode: INPUT_PULLUP
      inverted: True
    id: button
    on_press:
      - switch.toggle: relay

switch:
  - platform: gpio
    name: "${esphome_name}"
    pin: GPIO12
    id: relay

output:
  - platform: esp8266_pwm
    id: pow_blue_led
    pin:
      number: GPIO13
      inverted: yes

light:
  - platform: monochromatic
    output: pow_blue_led
    id: led
    internal: true

sensor:
  - platform: cse7766
    current:
      name: "${esphome_name} current"
      id: curr
    voltage:
      name: "${esphome_name} voltage"
      id: volt
    energy:
      name: "${esphome_name} energy"
      id: energy
    power:
      name: "${esphome_name} power"
      id: power

# switch ON
sun:
  latitude: !secret latitude
  longitude: !secret longitude
  # switch ON
  on_sunset:
  - then:
    - switch.turn_on: relay

# switch OFF
time:
  - platform: homeassistant
    id: homeassistant_time
    timezone: Europe/Prague
    on_time:
      # OFF Every evening
      - seconds: 00
        minutes: 00
        hours: 22
        days_of_week: MON-SUN
        then:
          - switch.turn_off: relay
